### ISSUE TITLE
Check required fields with a test [1h]

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#292] opened 2022-09-01 00:02 UTC
Once https://github.com/Gizra/drupal-starter/pull/291 is merged, create some test to check required fields using drupal_test_assertions

**Comment by amitaibu** [comment] 2022-09-01 05:37
Duplicate of https://github.com/Gizra/drupal-starter/issues/289

**Closed by amitaibu** 2022-09-01 05:37 UTC
